- name: Set timezone and configure NTP
  hosts: all
  become: yes
  tasks:
    - name: Set timezone
      command: timedatectl set-timezone {{ timezone }}
    - name: Set up NTP
      command: timedatectl set-ntp true
    - name: Set hardware clock from system clock
      command: hwclock --systohc
    - name: Install packages for all nodes
      community.general.pacman:
        name:
          - nfs-utils
          - net-tools
          - inetutils
        state: present
        upgrade_extra_args: "noconfirm"
    - name: Install open-iscsi package
      community.general.pacman:
        name:
          - open-iscsi
        state: present
        upgrade_extra_args: "noconfirm"
      register: result_all
      until: result_all.failed == false
      retries: 5
      delay: 10

- hosts: nfs
  become: true
  tasks:
    - name: Create export folder
      command: mkdir /srv/nfs/kubedata -p
    - name: Set permissions to nobody
      shell: "chown nobody: /srv/nfs/kubedata"
    - name: Ensure required entries are made to hosts file.
      lineinfile:
        path: /etc/exports
        state: present
        line: "{{ item }}"
      with_items:
        - "/srv/nfs/kubedata  *(rw,sync,no_subtree_check,no_root_squash,no_all_squash,insecure)"
    - name: Enable and start rpc-gssd service
      ansible.builtin.service:
        name: rpc-gssd
        enabled: yes
        state: restarted
    - name: Enable and start nfs service
      ansible.builtin.service:
        name: nfs-server
        enabled: yes
        state: restarted
    - name: Re-export the share
      command: exportfs -rav

- hosts: masters[0]
  become: false
  tasks:
    - name: Install helm on master node
      become: true
      community.general.pacman:
        name:
          - helm
        state: present
        upgrade_extra_args: "noconfirm"
    - name: Add nfs-subdir repo
      kubernetes.core.helm_repository:
        name: nfs-subdir-external-provisioner
        repo_url: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/"
    - name: Install nfs-subdir-external-provisioner with Helm
      kubernetes.core.helm:
        update_repo_cache: yes
        release_name: nfs-subdir-external-provisioner
        chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
        create_namespace: yes
        release_namespace: nfs
        release_values:
          nfs:
            server: "{{ hostvars['nfs-server']['ansible_facts']['eth0']['ipv4']['address'] }}"
            path: /srv/nfs/kubedata
    - name: Set nfs-client as the default storage class
      shell: |
        kubectl patch storageclass nfs-client -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
    - name: Add longhorn repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://charts.longhorn.io"
    - name: Install longhorn with Helm as secondary storage class
      kubernetes.core.helm:
        update_repo_cache: yes
        release_name: longhorn
        chart_ref: longhorn/longhorn
        create_namespace: yes
        release_namespace: longhorn-system
        release_values:
          persistence:
            defaultClass: false
